---
title: "Meeting Code of Conduct"
filename: code-of-conduct
toc: true
---

This Code of Conduct is intended to set clear expectations of behavior at the 2026 meeting of the SCO-SOC to ensure that all participants feel safe and welcome and that SCO-SOC 2026 is a positive experience for all.

The SCO-SOC welcomes everyone and celebrates diversity in all its forms. The SCO-SOC is dedicated to providing a collaborative, supportive, and engaging environment for everyone involved and that is free of discrimination, harassment, and retaliation. We expect all participants to help foster a respectful and considerate environment that provides constructive critique, debate, and interactions that respectfully allow for differences of opinion while embracing engaging discussion.


### Meeting Scope

We intend for SCO-SOC 2026 to foster open, honest and engaging communication of ornithological science. In so doing, we aim to promote equal opportunity and treatment for all participants. To achieve effective communication, we require attendees to conduct themselves in a courteous fashion and respect the intellectual property of our colleagues. We represent the field of ornithology, and it is imperative that we behave as professionals toward all conference participants, including, but not limited to, conference delegates, Council members, conference volunteers, sponsors, and exhibitors.

All forms of communication among conference participants during the meeting are considered within the scope of SCO-SOC 2026 and therefore fall under the Code of Conduct. These include public and private communications, social media posts, direct messages, phone calls, and other forms of written, verbal, and non-verbal (including visual) communication. Additionally, communication as described above occurring before or after the SCO-SOC 2026 meeting but pertaining to content associated with the meeting and/or relies on contact information of a meeting participant was procured before or during the meeting may also fall under the purview of this Code of Conduct. 

 
### Expectations of Participants

Harassment in any form between participants of SCO-SOC 2026 will not be tolerated. Harassment includes any communication with, or behavior towards another participant involving offensive gestures, verbal and written comments, posts on the internet and social media, deliberate intimidation, stalking, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical or electronic contact, microaggressions, and unwelcome attention. Note that it is also possible to unintentionally engage in harassment and participants must be mindful of their behavior. Participants asked to stop any harassing behavior by anyone are expected to comply immediately, regardless of their intent.

 
### Use of Media Associated With the Meeting

By registering for and attending this Meeting, Participants agree to allow SCO-SOC 2026 to use photos, videos, or audio recordings taken of them during the Meeting in publications, promotions, and on the websites and social media pages of the participating societies. Only the Society may (a) take/make or distribute audio or video recordings of the Meeting or Participants or (b) distribute them (via social media or other means).

Participants wishing to share information from the Event and/or post photos via social media, whether of their own material or that of others, must adhere to individual social media platforms’ stated rules and policies. We ask that presenters and hosts of Events that do not want content or information shared via social media clearly communicate this to members of the audience and that members of the audience adhere to such requests.

 
### Reporting an Incident

Any individual covered by the Code of Conduct who believes that they have been subjected to harassment, notices that someone else is being harassed, or has any other concerns about an individual’s behavior should report the incident immediately. Similarly, any breaches of the Code associated with media use should also be reported immediately. Potential violations of the Meeting Code of Conduct should be reported promptly to the SCO-SOC 2026 Safe Meeting Committee via email at <president@sco-soc.ca>. The Committee will strive to acknowledge all reports within one hour of receipt (between 9am to 5pm). All complaints will be taken seriously, promptly reviewed, and may be subject to investigation. Reports should be submitted using the group email, which will be directed to the entire Committee. All information related to the complaint and any subsequent investigation will be treated with the utmost confidentiality and shared only with Committee members as necessary to ensure a thorough and fair review.
 
### Disciplinary Action

Individuals found to have engaged in behavior prohibited by this policy, as well as those making bad faith allegations under the Code of Conduct will be subject to disciplinary action. The SCO-SOC 2026 Safe Meeting Committee may take any action they deem appropriate, ranging from a verbal warning or ejection/prohibition from the specific activity in question (e.g., workshop, symposium, or even the entire conference), banning them from future conferences run or jointly run by the partner societies, revoking membership in from the Society, and/or the reporting of their behavior to their employer and research funders.

 
### Retaliation Is Prohibited

Any form of retaliation—including seeking to violate the confidentiality of a reporting individual—against individuals who file a complaint or assist in an investigation or against any individuals suspected of doing so will not be tolerated by the SCO-SOC 2026 meeting. Retaliation is a serious violation of this policy and like any breach of the Code itself, will be subject to disciplinary action.

 
### Questions & Appeal

Any questions regarding this policy should be directed to the SCO-SOC 2026 Safe Meeting Committee. If an individual involved in any reported incident is dissatisfied with the disciplinary action, they may appeal to a committee made of the collective members of the executive committee from the Society.

 
### Social Media Policy

The 2026 meeting of the SCO-SOC supports the use of social media; we encourage thoughtful and considerate sharing of conference content. In our view, sharing ornithological science with the public via social media is one tool for public education and outreach and a key part of gaining long-term support for science and conservation. 

We encourage presenters to include personal and/or project social media handles, project hashtags or QR codes to external content on their slides (at least the opening/title slide, but recommended to use on all slides) and posters. For those without personal/project handles or hashtags, consider including the conference hashtag (#SCOSOC2026) or a social media icon on slides to let people know you are supportive of them posting about your work on social media.

Any presenters not wanting their presentation or research to be featured in social media posts must explicitly opt out of social media: this is best achieved by placing a “no social media” symbol on slides or materials. If presenters do not opt out in this manner, it shall be implied that conference organizers and/or attendees can share published research presented at the conference without consent. 

Anyone may participate in conversations on the host societies’ social media channels; however, please be aware that:

- Credit must be given to presenters/researchers whose presentation and/or research are featured in your post.
- The host society has the right to delete posts or comments containing spam, irrelevant remarks, or items that do not align with their mission/integrity.
- Personal attacks, promotion of violence or illegal activities, offensive material, or profanity will be deleted.

The host society reserves the right to ban users who violate this policy.

Conference attendees are expected to abide by the meeting code of conduct (above), and all those engaging on social media are asked to maintain apply the same respectful, courteous, inclusive, and supportive conduct online as in person to ensure a safe, hospitable, and productive conference. Discrimination, harassment, and/or retaliation will not be tolerated.

Additionally, we recommended that presenters and those sharing on social media be mindful of how photos of birds (and other animals) and their nests may appear to the public: Are safe and taxonomically appropriate grips being used? Does the bird appear in any way to be stressed, disheveled, or in an unnatural position? For suggestions on sharing photos of birds in the hand, see [guidelines provided by the North American Banding Council](https://nabanding.net/passerines/photographic-guidelines/). In addition, ask yourself if the use of a nest photo is helping to demonstrate something regarding your methods or results rather than just providing an interesting backdrop. For further guidelines on ethical photography of birds and their nests, see [Audubon's Guide to Ethical Bird Photography and Videography](https://www.audubon.org/get-outside/audubons-guide-ethical-bird-photography). 
