---
title: "Program"
filename: program
toc: true
format: 
  html:
    grid:
      body-width: 1200px
listing:
  - id: workshops-list
    contents: "workshops/*.qmd"
    type: default
    date-format: "h:mma z"
    sort: ["date","title"]
    filter-ui: true
    max-description-length: 150
    fields: [date, author, title, length, description]
    field-display-names:
      date: "Time"
      author: "Lead"
      length: "Length"
  - id: showcases-list
    contents: "showcases/*.qmd"
    type: default
    date-format: "h:mma z"
    sort: ["date","title"]
    filter-ui: true
    max-description-length: 150
    fields: [date, author, title, description]
    field-display-names:
      date: "Time"
      author: "Presenters"
---

### Program {.hide}

*The current schedule is **tentative** and subject to change.*

Schedule times are in your browser's local time.

::: {.program .list-table .squish}
- - Time
  - Monday (Oct 5)
  - Tuesday (Oct 6)
  - Wednesday (Oct 7)

- - {{< localtime 2026-10-05 11:00 EDT format='%H:%M %Z' >}}
  - []{rowspan=2} 
  - []{rowspan=2  .socialevents} Announcements / Social Event
  - []{rowspan=2  .socialevents} Announcements / Social Event

- - {{< localtime 2026-10-05 11:15 EDT format='%H:%M' >}}

- - {{< localtime 2026-10-05 11:30 EDT format='%H:%M' >}}
  - []{rowspan=8  .workshops} [Workshops](#workshops)
  - []{rowspan=10 .mainevents} Student Presentations
  - []{rowspan=3  .specialevents} [Plenary - Early Career Award Winner](#ECRA)

- - {{< localtime 2026-10-05 11:45 EDT format='%H:%M' >}}
- - {{< localtime 2026-10-05 12:00 EDT format='%H:%M' >}}
- - {{< localtime 2026-10-05 12:15 EDT format='%H:%M' >}}
  <!-- - []{rowspan=5  .mainevents} Research Showcase -->
  - []{.mainevents} [CanAvian: Advancing Avian Data Integration in Canada](showcases/showcase_abmi.qmd)

- - {{< localtime 2026-10-05 12:30 EDT format='%H:%M' >}} 
  - []{.mainevents} [Partners in Flight: Collaboration from Science to Application](showcases/showcase_pif.qmd)
- - {{< localtime 2026-10-05 12:45 EDT format='%H:%M' >}} 
  - []{.mainevents} [National Status and Trends of Canada’s Birds](showcases/showcase_cws_status.qmd)
- - {{< localtime 2026-10-05 13:00 EDT format='%H:%M' >}} 
  - []{.mainevents} [Banding in the Age of Technology](showcases/showcase_cws_banding.qmd)
- - {{< localtime 2026-10-05 13:15 EDT format='%H:%M' >}} 
  - []{.mainevents} [Twenty Years of Boreal Avian Modelling](showcases/showcase_bam.qmd)
- - {{< localtime 2026-10-05 13:30 EDT format='%H:%M' >}} 
  - []{rowspan=2  .socialevents} Break / Social Event
  - []{rowspan=2  .socialevents} Break / Social Event

- - {{< localtime 2026-10-05 13:45 EDT format='%H:%M' >}} 

- - {{< localtime 2026-10-05 14:00 EDT format='%H:%M' >}} 
  - []{rowspan=10 .workshops} [Workshops](#workshops)
  - []{rowspan=4  .socialevents} Break / Social Event
  <!-- - []{rowspan=6  .mainevents} Research Showcase -->
  - []{.mainevents} [Seabird Ecology at the Atlantic Laboratory for Avian Research](showcases/showcase_uofnb.qmd)

- - {{< localtime 2026-10-05 14:15 EDT format='%H:%M' >}} 
  - []{.mainevents} [Warblers to Waterbirds: Where and Why?](showcases/showcase_mcgill.qmd)

- - {{< localtime 2026-10-05 14:30 EDT format='%H:%M' >}} 
  - []{.mainevents} [Integrative Ornithology at AFAR](showcases/showcase_western.qmd)

- - {{< localtime 2026-10-05 14:45 EDT format='%H:%M' >}} 
  - []{.mainevents} [Avian Behaviour and Conservation Lab: Timing, Movement, and Conservation of Migratory Birds](showcases/showcase_uofm.qmd)

- - {{< localtime 2026-10-05 15:00 EDT format='%H:%M' >}} 
  - []{rowspan=4  .mainevents} Student Presentations
  - []{.mainevents} [Ecotoxicology and Conservation of Prairie Bird Communities](showcases/showcase_uofs.qmd)
  
- - {{< localtime 2026-10-05 15:15 EDT format='%H:%M' >}} 
  - []{.mainevents} [Landscape Change and Avian Ecology at Thompson Rivers University](showcases/showcase_tru.qmd)

- - {{< localtime 2026-10-05 15:30 EDT format='%H:%M' >}} 
  - []{rowspan=2  .socialevents} Break / Social Event

- - {{< localtime 2026-10-05 15:45 EDT format='%H:%M' >}} 

- - {{< localtime 2026-10-05 16:00 EDT format='%H:%M' >}} 
  - []{rowspan=4  .specialevents} Three-minute Thesis (3MT)
  <!-- - []{rowspan=5  .mainevents} Research Showcase -->
  - []{.mainevents} [Delivering Strong Science at Birds Canada](showcases/showcase_birds_canada.qmd)

- - {{< localtime 2026-10-05 16:15 EDT format='%H:%M' >}} 
  - []{.mainevents} [The Science that Powers Waterfowl Conservation](showcases/showcase_du.qmd)

- - {{< localtime 2026-10-05 16:30 EDT format='%H:%M' >}} 
  - []{rowspan=4  .specialevents} Annual General Meeting
  - []{.mainevents} [Ornithological research and conservation at the Ontario Ministry of Natural Resources](showcases/showcase_omnr.qmd)

- - {{< localtime 2026-10-05 16:45 EDT format='%H:%M' >}}
  - []{.mainevents} [Drivers of Migratory Bird Population Change in Working Landscapes](showcases/showcase_eccc_migration.qmd)

- - {{< localtime 2026-10-05 17:00 EDT format='%H:%M' >}}
  - []{rowspan=4  .socialevents} Networking Social
  - []{.mainevents} [Monitoring Bird Populations in Canada’s National Parks](showcases/showcase_parks_canada.qmd)

- - {{< localtime 2026-10-05 17:15 EDT format='%H:%M' >}}
  - []{.socialevents} Open Question Period / Break

- - {{< localtime 2026-10-05 17:30 EDT format='%H:%M' >}} 
  - []{rowspan=4  .socialevents} Social Event (?)
  - []{rowspan=2  .specialevents} Awards Ceremony 

- - {{< localtime 2026-10-05 17:45 EDT format='%H:%M' >}}
:::


## Early Career Research Award Plenary {#ECRA}

**From wingbeats to the twilight zone: how biologging has changed our perspective in marine ornithology**\
*Allison Patterson, Allison.patterson@ec.gc.ca*\
*Biodiversity Research Division, Environment and Climate Change Canada, Dartmouth, NS*

As a seabird biologist, I have spent untold hours in a blind observing birds return to their nests to feed their young and wondered “Where did they get that fish?” Ornithologists are fascinated by watching birds interact with their environment and share a common experience of mild disappointment when the object of our attention inevitably flies out of sight. Biologging shifts the perspective of our measurements from the observer to the individual bird. The proliferation of biologging technologies over the last 25 years has revolutionized how we study birds, allowing ornithologists to observe individual bird movements over large spatio-temporal scales and at increasingly fine resolution. Marine ornithology was historically constrained by the inherent challenges of observing birds at sea. Advances in biologging represent a sea change for seabird research, creating opportunities to empirically investigate questions in ecology that were inconceivable to previous generations of scientists.  I will present examples from my research – using wingbeat frequencies to measure foraging success, examining the energetics of foraging in the marine twilight zone by an Arctic seabird, and modelling year-round distributions of seabirds that migrate across the Atlantic Ocean – to discuss opportunities and challenges in using biologging to advance seabird ecology and support marine conservation.


## Workshops {#workshops .no-border}

**Monday, October 5th 2026**; Times are in Eastern Daylight Savings\
[*View all*](program_workshops.qmd)  

:::{#workshops-list}
:::

## Cross-Country Research Showcases {#showcases .no-border}

**Wednesday, October 7th 2026**; Times are in Eastern Daylight Savings\
[*View all*](program_showcases.qmd)  

:::{#showcases-list}
:::
