---
title: "Workshops"
filename: program_workshops
toc: true
---


## Integrating BirdNET Analyzer & Kaleidoscope Pro
**Lead**: Carlos Abrahams  
**Length**: 2-3 hours  

### Description

Combine BirdNET Analyzer and Kaleidoscope Pro for robust acoustic analysis, quality assurance (QA), and custom recogniser development. We will work through two real-world workflows: (i) running automated detections for birds in BirdNET, and then using Kaleidoscope Pro for efficient manual QA, and (ii) applying Kaleidoscope's clustering tools to generate high-quality training clips for building a custom amphibian BirdNET recognizer. Attendees will gain a clear introduction to how these two powerful software tools can be used together to leverage the strengths of each, creating an efficient and scalable workflow for acoustic monitoring. Designed for ecologists, bioacousticians, and practitioners, this Wildlife Acoustics workshop emphasizes practical skills, reproducible workflows, and confidence in automated acoustic monitoring results.

### Target audience

Ecologists, bioacousticians, and practitioners.

### Prerequisite skills/knowledge

General knowledge of Kaleidoscope and BirdNET are helpful for this workshop.

---

[*Return to Program*](program.qmd#workshops)

## Introduction to Quarto for Reproducibility
**Lead**: Steffi LaZerte  
**Length**: 2-2.5 hours  

### Description  
Do you struggle to keep track of your research analyses in R? Is future-self constantly complaining about past-self's inability to document scripts, data, and package versions? Come explore the magic of Quarto\! Turn your R scripts into reproducible reports complete with all the information future-self needs to write up your analyses.

In this workshop we'll learn about Markdown, RMarkdown and Quarto. We'll cover different ways of creating reports from scripts and how to customize the output to maximize beauty as well as reproducibility. You will have the opportunity to learn and practice, and will go home with a collection of resources to help you along your journey. Example scripts to work with will be available, but best is to bring your own. Note that while the focus of this workshop is on R, Quarto also works with Python, so feel free to bring Python scripts to play with as well.

Participants do not need to be R experts but should be somewhat familiar with R and an R IDE (e.g., RStudio or Positron). Instructions for installing these programs will be sent out before the workshop.

### Target audience  
Anyone who has a passing familiarity with R/Python and who would like to learn more about creating reproducible reports of their analyses.

### Prerequisite skills/knowledge  
Some familiarity with R and an R IDE (e.g., RStudio or Positron). Basic familiarity with R or Python is recommended.

---

[*Return to Program*](program.qmd#workshops)

## Introduction to stable-isotope assignment in R
**Lead**: Jackson Kusack  
**Length**: 2-2.5 hours  

### Description  
For migratory wildlife populations, understanding the connections between breeding, non-breeding, and stopover locations is integral to their conservation and management. Intrinsic markers, such as stable isotopes, found within the tissues of migratory individuals offer an alternative to the use of transmitters and other extrinsic markers. Briefly, this method relates the stable-isotope values of consumer tissues to those of the environment (especially stable isotopes of hydrogen and oxygen in precipitation) to determine likely origins where tissues were grown. In recent years there has been a handful of helpful packages released in the R statistical environment (isocat and AssignR) which have increased the functionality of these assignment methods and made them much more accessible.

In this workshop, I will first present a short introduction to the theory behind stable-isotope assignment, after which we will work through an example R script where we will, step-by-step, work though the procedures to determine the likely origins of unknown-origin migrants. No data is required by participants as everything will be provided during the workshop, but participants are welcome to apply the code to their own data.

The expected outcome for this workshop is that participants will gain a better understanding for the general approach and theory behind stable-isotope assignment using hydrogen isotopes and leave with some fundamental R code to build upon for their own analyses.

### Target audience  
Researchers and students who are interested in or are planning to collect tissues for stable isotope assignment. This workshop is aimed at a general audience.

### Prerequisite skills/knowledge  
Some familiarity with R/Rmarkdown is suggested.

---

[*Return to Program*](program.qmd#workshops)

## Modeling Breeding Bird Survey with bbsBayes2: status, trends, and causal modeling of drivers of trends
**Lead**: Adam Smith  
**Length**: 2-2.5 hours  

### Description

[bbsBayes2](https://bbsbayes.github.io/bbsBayes2) is an R-package that allows for easy access to the North American Breeding Bird Survey data and for fitting a selection of hierarchical Bayesian models that estimate status and trends and can be modified to estimate the influence of spatial and temporal predictors on trends and abundance (e.g., [Mckellar et al. 2025](https://doi.org/10.1675/063.048.0203) and [Smith et al. 2024](https://doi.org/10.1093/ornithapp/duad056)). The package provides efficient, fully-Bayesian parameter estimation using Stan, spatially explicit models well suited to exploring spatial patterns in trends, and options to customize models to include covariates of trends and abundance. The package also allows for a streamlined Bayesian workflow that facilitates convergence diagnostics, prior and posterior predictions, visualization of model predictions, as well as cross-validation and model comparisons.

During this workshop you will follow along with live coding to get hands-on experience manipulating and visualizing output from a range of models and species. We will demonstrate the package's functions, including those that allow you to:

1. Prepare the data for modeling a given species and fit a model that estimates trends for any time period (1970-2019, 2005-2015, 1980-2000, etc.).  
2. Generate heat maps of population trends and graph population trajectories.  
3. Choose from a suite of built-in hierarchical Bayesian models and access tools to help with cross-validation and model comparison.  
4. Estimate trends for customized regions (e.g., all of the eastern Boreal, Great Plains versus eastern populations of grassland birds).  
5. Build and fit customized models: the workshop allows plenty of time to explore customizing the base-models with examples of models that estimate regional climate-effects on population trends, local landcover effects on mean abundance, landcover change effects on trends, etc.

### Target audience 

 Researchers and students interested in:

1. modeling spatial and temporal patterns in bird population over the last 60 years;  
2. modeling covariates or causal drivers of variations in abundance and trends;  
3. gaining experience in Bayesian workflow and fitting models using Stan;  
4. better understanding the models used by the Canadian Wildlife Service, and the United States Geological Survey to estimate status and trends from BBS data.

### Prerequisite skills/knowledge

Familiarity with coding in R is necessary. No prior experience with Stan or Bayesian models is required.

---

[*Return to Program*](program.qmd#workshops)

## Modelling Avian Habitat Ecology
**Lead**: Andy Crosby  
**Length**: Full day / 4-5 hours  

### Description  
Much of the research conducted on birds involves, either explicitly or implicitly, modelling patterns of habitat use in order to understand species ecology and the potential effects of land-use and climate change on populations. Patterns of habitat use by birds are the realization of the habitat selection process, which is governed by the interaction of individual species ecology and landscape ecological context. The purpose of this workshop is to provide a basic understanding of how habitat modelling techniques, such as occupancy modelling and resource selection functions, can be used to make valid inferences about species ecology and habitat selection. 

In this workshop we will use a combination of interactive lectures and hands on work in R to: 

1. Gain an understanding of basic principles of avian habitat ecology;   
2. Understand habitat modelling theory in terms of habitat use, availability, preference, and selection; and   
3. Understand how occupancy models and resource selection functions operate to provide inferences about occupancy patterns and drivers of habitat selection.

An important aspect of this workshop will be using simple data simulations to better understand the data generation process and how it interacts with the models to produce the results we see. This will allow participants to better understand and interpret model outputs in their ecological context Thus, the focus of this workshop will be less on how to run models, and more on using the models to gain reliable knowledge about important ecological processes. I will provide some example datasets, and participants are welcome to use their own data to work with the models. 

Expected outcomes will be a better knowledge of avian habitat ecology and increased ability to understand and properly utilize common habitat modelling techniques for research and conservation. 

### Target audience  
Students and professionals looking for a deeper understanding of habitat ecology and how modelling can be used to understand avian habitat selection.

### Prerequisite skills/knowledge  
Basic R skills and understanding of generalized linear models. Understanding for-loops will be particularly important. I will send preliminary material to familiarize participants with necessary concepts ahead of time. 

---

[*Return to Program*](program.qmd#workshops)

## Regulating incidental take in Canada: challenges and opportunities for scientists
**Lead**: Julie Bourque  
**Length**: 2-2.5 hours  

### Description  
Despite the federal prohibition on killing migratory birds and destroying their nests, approximately 269 million birds are killed and almost one million nests are destroyed annually in Canada due to otherwise lawful human activities. Bird mortality results from window collisions, fisheries bycatch, powerline electrocution, among other causes. Nest destruction is primarily associated with vegetation management activities during the breeding season including both temporary activities such as agriculture or forestry and permanent land conversion such as urbanization. This unintentional (incidental) take includes almost all spheres of human activities, both industrial and non-industrial, and is expected to increase as human development accelerates.

In the last few years, there has been renewed interest in regulating incidental take at the federal level. A regulatory system could provide benefits to migratory birds through the universal adoption of beneficial management practices in exchange for more legal certainty. However, such an initiative requires a strong scientific foundation to ensure that decision-making achieves conservation goals. For example, understanding the scope and impact of an activity is essential for establishing a baseline against which mitigation measures can be evaluated. Further research is also needed to evaluate evidence-based mitigation measures and their applicability in the Canadian context.

This workshop will examine the concept of incidental take and will aim to foster discussion on how scientists can influence regulatory and policy development through their research. The workshop will include a presentation followed by an open discussion with participants. The expected outcome is that participants will gain a better understanding of how to present the results of their research to policymakers to better support policy development for migratory birds in Canada. The workshop may also help researchers incorporate incidental take considerations into their work and strengthen collaboration between scientists and policymakers.

### Target audience  
The target audience consists of researchers with an interest in policy-making and with knowledge on the effects of human activities on migratory birds.

### Prerequisite skills/knowledge  
Some prior knowledge of the prohibitions of the Migratory Birds Convention Act and the Migratory Birds Regulations 2022 is useful.


---

[*Return to Program*](program.qmd#workshops)

## Using WildTrax to manage and process your birdsong recordings
**Lead**: Kevin Kelly  
**Length**: Full day / 4-5 hours  


### Description  
WildTrax is a free online platform developed to remove the barrier of entry for researchers and managers to manage and process ARU recordings at any scale of research program. Developed to help users manage and process acoustic data from raw recordings through to being used in statistical analyses, WildTrax allows users to store raw data, metadata, and derived species data on a cloud system that can be shared by collaborators anywhere in the world. With standardized metadata formats, processing methods and report outputs, the data can be easily stored and shared between users.

In this workshop we'll teach you how to upload and manage acoustic recordings; store and manage metadata such as survey locations, field site visits, and field equipment information; process the recordings to identify the species vocalizing in the recordings; create and manage projects to aggregate your data into collective reports; use the built in birdsong recognizers (BirdNET and HawkEars) to enhance your processing abilities; and publish, share and download the data contained on WildTrax.

The workshop is set-up to be interactive so that users can follow along on the WildTrax platform to perform the various steps being presented using their own data or example data provided by the facilitators to learn the various features and functions available in WildTrax.

### Target audience  
This workshop is meant to appeal to novice passive acoustic monitoring users (basic understanding of an ARU and spectrogram) to a more experienced researcher wanting to learn how WildTrax can help with their data storage and processing needs.

### Prerequisite skills/knowledge  
Basic understanding of passive acoustic recordings and spectrograms is helpful.
