---
title: "Code de conduite de la conférence"
filename: code-of-conduct
toc: true
---

Ce code de conduite vise à établir des attentes claires en matière de comportement lors de la conférence de la SCO-SOC de 2026 afin de garantir que tous les participants se sentent en sécurité et bien accueillis, et que SCO-SOC 2026 soit une expérience positive pour tous. 

La SCO-SOC accueille tout le monde et célèbre la diversité sous toutes ses formes. La SCO-SOC s’engage à offrir un environnement collaboratif, solidaire, et stimulant pour tous les participants, exempt de discrimination, de harcèlement et de représailles. Nous attendons de tous les participants qu’ils contribuent à créer un climat respectueux et attentif, qui permette des critiques constructives, des débats et des interactions respectueuses des différences d’opinion, tout en favorisant des discussions enrichissantes.

### Portée de la conférence

Il est notre intention que la SCO-SOC 2026 favorise une communication ouverte, honnête, et engageante de la science ornithologique. Ce faisant, nous visons à promouvoir l’égalité des chances et un traitement équitable pour tous les participants. Pour assurer une communication efficace, nous demandons aux participants de se montrer courtois et de respecter la propriété intellectuelle de nos collègues! Nous représentons le domaine de l’ornithologie, et il est essentiel que nous agissions en professionnels envers tous les participants de la conférence, y compris, mais sans s’y limiter, les délégués, les membres du Conseil, les employés de la société, les bénévoles de la conférence, les commanditaires et les exposants. 

Toutes les formes de communication entre participants à la conférence sont considérées comme entrant dans le champ d'application de SCO-SOC 2026 et relèvent donc du Code de conduite. Il s'agit notamment des communications publiques et privées, des publications sur les réseaux sociaux, des messages directs, des appels téléphoniques et d'autres formes de communication écrite, verbale et non verbale (y compris visuelle). De plus, les communications décrites ci-dessus qui ont lieu avant ou après la conférence SCO-SOC 2026, mais qui concernent le contenu associé à la conférence et/ou qui reposent sur les coordonnées d'un participant à la conférence qui ont été obtenues avant ou pendant la conférence peuvent également relever du présent Code de conduite.

### Attentes des participants

Le harcèlement sous quelque forme que ce soit entre les participants à SCO-SOC 2026 ne sera pas toléré. Le harcèlement comprend toute communication ou tout comportement envers un autre participant impliquant des gestes offensants, des commentaires verbaux et écrits, des publications sur Internet et les médias sociaux, de l'intimidation délibérée, du harcèlement criminel, des photographies ou des enregistrements harcelants, une perturbation soutenue des discussions ou d'autres événements, des contacts physiques ou électroniques inappropriés, des micro-agressions et une attention importune. Notez qu'il est également possible de s'engager involontairement dans le harcèlement et que les participants doivent être conscients de leur comportement. Nous nous attendons à ce que les participants à qui l’on demande de mettre fin à tout comportement harcelant de la part de quiconque s'y conforment immédiatement, quelle que soit leur intention.

### Utilisation des médias associés à la conférence

En s'inscrivant et en assistant à cette conférence, les participants acceptent de permettre à SCO-SOC 2026 d'utiliser des photos, des vidéos ou des enregistrements audio pris d'eux pendant la conférence dans des publications, des promotions ainsi que sur les sites Web et les pages de médias sociaux des sociétés participantes. Seule la Société peut (a) capturer ou faire des enregistrements audio ou vidéo de la conférence ou des participants, ou (b) les distribuer (via les médias sociaux ou d'autres moyens)

Les participants souhaitant partager des informations de l'événement et/ou publier des photos via les réseaux sociaux, que ce soit de leur propre matériel ou de celui des autres, doivent respecter les règles et politiques énoncées des différentes plateformes de médias sociaux. Nous demandons aux présentateurs et aux hôtes des événements qui ne souhaitent pas que leur contenu ou leurs informations soient partagés sur les réseaux sociaux de le communiquer clairement aux membres de l'audience, et nous demandons aux membres de l'audience de respecter ces demandes.

### Signaler un incident

Toute personne couverte par le Code de conduite qui estime avoir été victime de harcèlement, remarque qu'une autre personne est harcelée ou a des préoccupations concernant le comportement d'une personne, doit signaler l'incident immédiatement. De même, toute violation du Code liée à l'utilisation des médias doit également être signalée sans délai. Les violations potentielles du Code de conduite de la conférence doivent être signalées rapidement au Comité pour une conférence sécuritaire de la SCO-SOC 2026 à l’adresse courriel <president@sco-soc.ca>. Le Comité s’efforcera d’accuser réception de tout signalement dans l’heure suivant sa réception. Toutes les plaintes seront prises au sérieux, examinées rapidement et pourraient faire l’objet d’une enquête. Les signalements doivent être envoyés à l’adresse courriel du groupe, ce qui permettra à l’ensemble du Comité d’y avoir accès. Toutes les informations concernant la plainte et toute enquête subséquente seront traitées avec la plus grande confidentialité et ne seront partagées qu’avec les membres du Comité lorsque nécessaire afin d’assurer un examen rigoureux et équitable.

### Mesure disciplinaire

Les personnes reconnues coupables d'avoir adopté un comportement interdit par cette politique, ainsi que celles formulant des allégations de mauvaise foi en vertu du Code de conduite, seront sujettes à des mesures disciplinaires. Le Comité pour une conférence sécuritaire de la SCO-SOC 2026 peut prendre toute mesure qu'il juge appropriée, allant d'un avertissement verbal à l'expulsion ou l'interdiction de participer à l'activité en question (p. ex., atelier, symposium ou même l'ensemble de la conférence), l'interdiction de participer aux futures conférences organisées ou co-organisées par les sociétés partenaires, la révocation de l'adhésion à la Société et/ou le signalement de leur comportement à leur employeur et aux organismes de financement de la recherche.

### Les représailles sont interdites

Toute forme de représailles, y compris la tentative de violation de la confidentialité d'une personne ayant signalé un incident, envers les personnes qui déposent une plainte, assistent à une enquête, ou sont soupçonnées de le faire, ne sera pas tolérée lors de la conférence SCO-SOC 2026. Les représailles constituent une violation grave de cette politique et, comme toute infraction au Code lui-même, feront l'objet de mesures disciplinaires.

### Questions et appels

Toute question concernant cette politique doit être adressée au Comité pour une conférence sécuritaire de la SCO-SOC 2026. Si une personne impliquée dans un incident signalé n'est pas satisfaite de la mesure disciplinaire, elle peut faire appel auprès d'un comité composé des membres collectifs du comité exécutif de la Société.

### Politiques sur les médias sociaux

La conférence SCO-SOC 2026 encourage l'utilisation des médias sociaux; nous incitons au partage réfléchi et respectueux du contenu de la conférence. Selon nous, partager la science ornithologique avec le public via les médias sociaux est un outil important pour l'éducation et la sensibilisation du public, ainsi qu'un élément clé pour obtenir un soutien à long terme pour la science et la conservation.

Nous encourageons les présentateurs à inclure leurs identifiants de médias sociaux personnels et/ou de projet, des mot-clics de projet ou des codes QR menant à des contenus externes sur leurs diapositives (au moins sur la diapositive d'ouverture/titre, mais il est recommandé de les utiliser sur toutes les diapositives) et sur leurs affiches. Pour ceux qui n'ont pas d'identifiants ou de mot-clics personnels/projets, envisagez d'inclure le mot-clic de la conférence (#SCOSOC2026) ou une icône de réseau social sur les diapositives pour indiquer que vous soutenez le partage de votre travail sur les médias sociaux.

Tout présentateur ne souhaitant pas que sa présentation ou ses recherches soient partagées sur les médias sociaux doit explicitement se retirer de cette option: cela se fait le mieux en plaçant un symbole « pas de médias sociaux » sur les diapositives ou les documents. Si les présentateurs ne se retirent pas de cette manière, il sera sous-entendu que les organisateurs de la conférence et/ou les participants peuvent partager les recherches publiées présentées lors de la conférence sans consentement.

Toute personne peut participer aux conversations sur les canaux de médias sociaux des sociétés hôtes; toutefois, veuillez noter que: 

- Le crédit doit être accordé aux présentateurs/chercheurs dont la présentation et/ou les recherches sont mises de l’avant dans votre publication.
- La société hôte a le droit de supprimer les publications ou commentaires contenant du spam, des remarques non pertinentes ou des éléments qui ne sont pas en accord avec sa mission/intégrité. 
- Les attaques personnelles, la promotion de la violence ou d'activités illégales, les contenus offensants ou les propos vulgaires seront supprimés.

La société hôte se réserve le droit d'interdire l'accès aux utilisateurs qui enfreignent cette politique.

Les participants à la conférence sont tenus de respecter le code de conduite de la conférence (section précédente), et tous ceux qui interagissent sur les médias sociaux sont invités à adopter le même comportement respectueux, courtois, inclusif et bienveillant en ligne, afin de garantir une conférence sûre, accueillante et productive. La discrimination, le harcèlement et/ou les représailles ne seront pas tolérées.

De plus, nous recommandons aux présentateurs et à ceux qui partagent des informations sur les médias sociaux de faire attention à la manière dont les photos d'oiseaux (et d'autres animaux) et de leurs nids peuvent être perçues par le public; des prises sûres et taxonomiquement appropriées sont-elles utilisées? L'oiseau semble-t-il stressé, ébouriffé ou dans une position non naturelle? Pour des suggestions sur le partage de photos d'oiseaux en main, consultez les [lignes directrices fournies par le North American Banding Council](https://nabanding.net/passerines/photographic-guidelines/). Demandez-vous également si l'utilisation d'une photo de nid sert à illustrer quelque chose concernant vos méthodes ou résultats plutôt qu'à offrir simplement un décor intéressant. Pour d'autres lignes directrices sur la photographie éthique des oiseaux et de leurs nids, consultez "[Audubon's Guide to Ethical Bird Photography and Videography](https://www.audubon.org/get-outside/audubons-guide-ethical-bird-photography)".
